name: Build
on:
  push:
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Ninja
          c-compiler: gcc
          cxx-compiler: g++

      - name: Configure CMake
        run: cmake --preset debug
        
      - name: Build the project
        run: cmake --build --preset debug
        
